"""Initial migration with all tables

Revision ID: be199617c00b
Revises:
Create Date: 2025-10-20 08:31:54.445054

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be199617c00b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ledger_journals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_ref", sa.String(length=100), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    with op.batch_alter_table("ledger_journals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ledger_journals_external_ref"),
            ["external_ref"],
            unique=False,
        )

    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("delivered", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "communities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=True),
        sa.Column("owner_user_id", sa.Integer(), nullable=True),
        sa.Column("settings_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("communities", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_communities_slug"), ["slug"], unique=True)

    op.create_table(
        "campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("target_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"], ["communities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "community_invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("inviter_user_id", sa.Integer(), nullable=True),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"], ["communities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["inviter_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("community_invites", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_community_invites_token"), ["token"], unique=True
        )

    op.create_table(
        "community_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"], ["communities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("community_id", "user_id", name="uq_community_member"),
    )
    op.create_table(
        "contributions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("contribution_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"], ["communities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contributions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_contributions_community_id", ["community_id"], unique=False
        )
        batch_op.create_index(
            "idx_contributions_created_at", ["created_at"], unique=False
        )
        batch_op.create_index(
            "idx_contributions_type", ["contribution_type"], unique=False
        )
        batch_op.create_index("idx_contributions_user_id", ["user_id"], unique=False)

    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("journal_id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("account_code", sa.String(length=50), nullable=False),
        sa.Column("debit", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("credit", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["journal_id"], ["ledger_journals.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("community_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.String(length=300), nullable=False),
        sa.Column("secret", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"], ["communities.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Make otp_verifications compatible with pre-existing schemas
    # Check if table exists before modifying
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if "otp_verifications" in existing_tables:
        # Add otp_hash if missing, and safely drop legacy index/column if present
        op.add_column(
            "otp_verifications",
            sa.Column("otp_hash", sa.String(length=255), nullable=True),
        )
        op.execute("DROP INDEX IF EXISTS idx_otp_phone")
        op.execute("DROP INDEX IF EXISTS idx_otp_phone_number")
        op.execute("ALTER TABLE otp_verifications DROP COLUMN IF EXISTS otp_code")

    # Safely drop legacy transaction indexes if they exist, then create FK
    if "transactions" in existing_tables:
        op.execute("DROP INDEX IF EXISTS idx_transactions_destination_wallet")
        op.execute("DROP INDEX IF EXISTS idx_transactions_reference")
        op.execute("DROP INDEX IF EXISTS idx_transactions_source_wallet")
        # Check if contribution_id column exists before adding FK
        columns = [col["name"] for col in inspector.get_columns("transactions")]
        if "contribution_id" in columns:
            with op.batch_alter_table("transactions", schema=None) as batch_op:
                batch_op.create_foreign_key(
                    None,
                    "contributions",
                    ["contribution_id"],
                    ["id"],
                    ondelete="SET NULL",
                )

    # Drop legacy users indexes if they exist
    if "users" in existing_tables:
        op.execute("DROP INDEX IF EXISTS idx_users_email")
        op.execute("DROP INDEX IF EXISTS idx_users_phone")

    # Drop legacy wallets indexes if they exist
    if "wallets" in existing_tables:
        op.execute("DROP INDEX IF EXISTS idx_wallets_display_number")
        op.execute("DROP INDEX IF EXISTS idx_wallets_user_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wallets", schema=None) as batch_op:
        batch_op.create_index("idx_wallets_user_id", ["user_id"], unique=False)
        batch_op.create_index(
            "idx_wallets_display_number", ["display_number"], unique=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("idx_users_phone", ["phone_number"], unique=False)
        batch_op.create_index("idx_users_email", ["email"], unique=False)

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_index(
            "idx_transactions_source_wallet", ["source_wallet_id"], unique=False
        )
        batch_op.create_index(
            "idx_transactions_reference", ["reference_number"], unique=False
        )
        batch_op.create_index(
            "idx_transactions_destination_wallet",
            ["destination_wallet_id"],
            unique=False,
        )

    with op.batch_alter_table("otp_verifications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "otp_code", sa.VARCHAR(length=6), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("otp_hash")

    # Create index if it doesn't exist
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_otp_phone ON otp_verifications (phone_number)"
    )

    op.drop_table("webhooks")
    op.drop_table("ledger_entries")
    with op.batch_alter_table("contributions", schema=None) as batch_op:
        batch_op.drop_index("idx_contributions_user_id")
        batch_op.drop_index("idx_contributions_type")
        batch_op.drop_index("idx_contributions_created_at")
        batch_op.drop_index("idx_contributions_community_id")

    op.drop_table("contributions")
    op.drop_table("community_members")
    with op.batch_alter_table("community_invites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_community_invites_token"))

    op.drop_table("community_invites")
    op.drop_table("campaigns")
    with op.batch_alter_table("communities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_communities_slug"))

    op.drop_table("communities")
    op.drop_table("webhook_events")
    with op.batch_alter_table("ledger_journals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ledger_journals_external_ref"))

    op.drop_table("ledger_journals")
    # ### end Alembic commands ###
