"""Add wallet owner_type and owner_id for Phase 2

Revision ID: c2f0ca1745c9
Revises: be199617c00b
Create Date: 2025-11-02 17:29:44.960705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'c2f0ca1745c9'
down_revision = 'be199617c00b'
branch_labels = None
depends_on = None


def column_exists(table_name, column_name):
    """Check if a column exists in a table"""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def constraint_exists(table_name, constraint_name):
    """Check if a constraint exists on a table"""
    bind = op.get_bind()
    # Use parameterized query with proper escaping
    query = sa.text(
        f"SELECT conname FROM pg_constraint WHERE conrelid = '{table_name}'::regclass AND conname = :constraint_name"
    )
    result = bind.execute(query.bindparams(sa.bindparam('constraint_name', constraint_name)))
    return result.fetchone() is not None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_value', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklists_entity_value'), ['entity_value'], unique=False)

    op.create_table('settlement_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aml_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('case_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_development_funds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('education_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('health_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('welfare_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('general_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('contribution_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('total_contributed', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id')
    )
    op.create_table('multisig_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('operation_ref', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('destination', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('required_signatures', sa.Integer(), nullable=True),
    sa.Column('approval_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payer_wallet_id', sa.Integer(), nullable=True),
    sa.Column('payee_wallet_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_ref', sa.String(length=200), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['ledger_journals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payee_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payer_wallet_id'], ['wallets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_provider_ref'), ['provider_ref'], unique=False)

    op.create_table('community_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('contribution_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('contribution_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('allocated_to', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['journal_id'], ['ledger_journals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multisig_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signature_type', sa.String(length=20), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['multisig_approvals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('transaction_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('community_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('federal_fee', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['journal_id'], ['ledger_journals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.alter_column('otp_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_index('idx_otp_expires_at')
        batch_op.create_index(batch_op.f('ix_otp_verifications_phone_number'), ['phone_number'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'SUCCESS'::character varying"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index('idx_users_reset_token')

    # Check if columns and constraints exist before trying to modify them
    owner_type_exists = column_exists('wallets', 'owner_type')
    owner_id_exists = column_exists('wallets', 'owner_id')
    constraint_exists_flag = constraint_exists('wallets', 'wallets_user_id_key')
    
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        # Only add columns if they don't already exist
        if not owner_type_exists:
            batch_op.add_column(sa.Column('owner_type', sa.String(length=20), nullable=False, server_default='USER'))
        if not owner_id_exists:
            batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False, server_default='0'))
        
        # These operations are safe to run even if columns already exist
        try:
            batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        except Exception:
            pass  # Column may already be nullable
        
        try:
            batch_op.alter_column('wallet_number',
                   existing_type=sa.UUID(),
                   type_=sa.String(length=36),
                   existing_nullable=True,
                   existing_server_default=sa.text('gen_random_uuid()'))
        except Exception:
            pass  # Column type may already be correct
        
        # Only drop constraint if it exists
        if constraint_exists_flag:
            try:
                batch_op.drop_constraint('wallets_user_id_key', type_='unique')
            except Exception:
                pass  # Constraint may have been dropped already
    
    # Update existing rows if columns were just added (after batch_alter_table context)
    if not owner_type_exists or not owner_id_exists:
        bind = op.get_bind()
        if not owner_type_exists:
            bind.execute(sa.text("UPDATE wallets SET owner_type = 'USER' WHERE owner_type IS NULL OR owner_type = ''"))
        if not owner_id_exists:
            bind.execute(sa.text("UPDATE wallets SET owner_id = COALESCE(user_id, 0) WHERE owner_id IS NULL OR owner_id = 0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_unique_constraint('wallets_user_id_key', ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('wallet_number',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=True,
               existing_server_default=sa.text('gen_random_uuid()'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('owner_id')
        batch_op.drop_column('owner_type')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_reset_token', ['reset_token'], unique=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'SUCCESS'::character varying"))

    with op.batch_alter_table('otp_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_verifications_phone_number'))
        batch_op.create_index('idx_otp_expires_at', ['expires_at'], unique=False)
        batch_op.alter_column('otp_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    op.drop_table('transaction_fees')
    op.drop_table('multisig_signatures')
    op.drop_table('community_contributions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_provider_ref'))

    op.drop_table('payments')
    op.drop_table('multisig_approvals')
    op.drop_table('community_development_funds')
    op.drop_table('aml_cases')
    op.drop_table('settlement_batches')
    with op.batch_alter_table('blacklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklists_entity_value'))

    op.drop_table('blacklists')
    # ### end Alembic commands ###
