# cd to db folder and run: docker-compose up -d
# access pgadmin at: http://localhost:5050
# access redis commander at: http://localhost:8081
services:
  postgres:
    image: postgres:15
    container_name: kingdompay_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Kingdompay@2025
      POSTGRES_DB: kingdompay
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d kingdompay"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: kingdompay_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: kingdompay_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kingdompay.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: kingdompay_redis_commander
    restart: always
    environment:
      REDIS_HOSTS: local:redis:6379:0
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
